name: Atualizar estatísticas do README

on:
  schedule:
    - cron: "0 3 * * *" # diariamente
  workflow_dispatch:

jobs:
  gerar-cards:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Gerar estatísticas do GitHub
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: stats
          options: username=pehaalmeida&show_icons=true&theme=transparent&hide_border=true
          path: assets/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Gerar linguagens mais usadas
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=pehaalmeida&layout=compact&theme=transparent&hide_border=true&langs_count=8
          path: assets/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commitar arquivos gerados
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add assets/*.svg
          git commit -m "Atualiza estatísticas do README" || exit 0
          git push
